name: Cloudflare Radar

on:
  schedule:
    - cron: '5 0,6,12,18 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: james-atkins/cloudflare-radar
          token: ${{ secrets.PAT }}
          path: data
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Scrape
        run: python cloudflare_radar.py
      - name: Commit and push
        run: |-
          cd data
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
